### ISSUE TITLE
Use Requests.py instead of urllib for API calls

### ISSUE THREAD

**Issue by ndanielsen** [ndanielsen/py-votesmart#5]
- Add requests to requirements.txt

- Rework `_apicall` to utilize requests.py for auth and url requests

- Remove `urllib.request import urlopen` related code

**Comment by mtnwni** [comment]
Hey @ndanielsen I would like to take this one, do you have any contribution guidelines? I couldn't find anything related to contributions in the readme.

**Comment by mtnwni** [comment]
sent you a pull request.

**Comment by ndanielsen** [comment]
@skepticleo thank you so much for coming here and wanting to contribute! 

This fork is about 24 hours old at the moment. I'm still working on getting tests, documentation and contribution guidelines setup. 

As soon as I have a bit more set up, I'll take a look at your PR https://github.com/ndanielsen/py-votesmart/pull/7 and follow up from there.

Thanks again!

**Comment by ndanielsen** [comment]
https://github.com/ndanielsen/py-votesmart/pull/9
